[package]
name = "icrc99.mo"
version = "0.0.1"
description = "The reference implementation for ICRC-99."
repository = "https://github.com/icdevsorg/icrc99.mo"

[dependencies]
base = "0.13.0"
vector = "0.4.1"
candy = "0.3.0"
map = "9.0.1"
encoding = "https://github.com/aviate-labs/encoding.mo#v0.4.1"
serde = "3.2.1"
sha3 = "0.1.1"
sha2 = "0.1.0"
tecdsa = "0.0.4"
icrc7-mo = "0.4.1"
icrc37-mo = "0.4.2"
stableheapbtreemap = "1.5.0"
